export const getMockupTypes = (default_options) => {
  const findSignType = (key) =>
    default_options?.sign_type?.find((item) => item.key === key)?.name || "";

  return [
    {
      name: findSignType("sign_type_halo_lit_letters"),
      signType: "halo-lit-channel",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_face_lit_letters"),
      signType: "face-lit-channel",
      mountingType: "flush",
      faceLitTrimStyle: "trim",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
      faceLitReturnColor: "logo-match",
    },
    {
      name: findSignType("sign_type_fabricated_letters_non_lit"),
      signType: "fabricated-non-lit",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
      fabricatedFinish: "goldenMirror",
    },
    {
      name: findSignType("sign_type_neon_sign"),
      signType: "led-neon",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_single_sided_lightbox"),
      signType: "cut-to-shape-light-box",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_marquee_channel_letters"),
      signType: "marquee-channel",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_flat_cut_aluminum_letters"),
      signType: "flat-cut-pasted",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_standard_face_lit_plastic_trim_letters"),
      signType: "face-lit-channel",
      mountingType: "flush",
      faceLitTrimStyle: "trim",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
      faceLitReturnColor: "logo-match",
    },
    {
      name: findSignType("sign_type_face_and_halo_lit_letters"),
      signType: "face-and-halo-lit-channel",
      mountingType: "flush",
      faceLitTrimStyle: "trim",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
      faceLitReturnColor: "logo-match",
    },
    {
      name: findSignType("sign_type_neon_acrylic_sign"),
      signType: "led-neon",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    // {
    //   name: findSignType("sign_type_fabricated_letters_non_lit"),
    //   signType: "fabricated-non-lit",
    //   mountingType: "flush",
    //   xPercent: 50,
    //   yPercent: 50,
    //   signSize: 100,
    //   isLightingOn: true,
    //   fabricatedFinish: "silverBrushed",
    // },
    {
      name: findSignType("sign_type_metal_on_acrylic"),
      signType: "flat-cut-pasted",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    
    {
      name: findSignType("sign_type_open_face_neon_channel_letters"),
      signType: "open-face-neon-channel",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_flat_cut_acrylic_letters"),
      signType: "flat-cut-pasted",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    
    {
      name: findSignType("sign_type_double_sided_lightbox"),
      signType: "blade-projecting-sign-double-sided",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_3d_blade_sign"),
      signType: "blade-projecting-sign-bracket-mounted",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_2d_blade_sign"),
      signType: "blade-projecting-sign-bracket-mounted",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_single_sided_push_through"),
      signType: "push-through-face-lit",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_double_sided_push_through_cabinet"),
      signType: "push-through-halo-lit",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_mirror_infinity_channel_letters"),
      signType: "infinity-mirror-channel",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_face_and_side_lit_letters"),
      signType: "side-lit-channel",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_a_frame_sign"),
      signType: "a-frame-sign",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
    {
      name: findSignType("sign_type_vinyl_banners"),
      signType: "vinyl-graphics-wall-wraps-full",
      mountingType: "flush",
      xPercent: 50,
      yPercent: 50,
      signSize: 100,
      isLightingOn: true,
    },
  ];
};
